// reasons.js — 365 reasons, one per day
// for Sinthia, from Babai

window.REASONS = [
  "I don't know how to explain it but the day I met you something just clicked into place. Like oh. There you are.",
  "You play guitar like you've known those strings your whole life. I could sit and just watch your hands for hours.",
  "The way you walk into a library — like you own the place but also like it's sacred. Both at once. That's very you.",
  "You hum when you're not paying attention. You probably don't even know you do it. I notice every single time.",
  "Fast food with you goes from a meal to an event. You take it seriously and I find that so endearing.",
  "I think about the distance a lot. And then I think about you and it somehow feels smaller.",
  "You're not easy to impress and that's one of my favorite things about you. It means something when I manage it.",
  "You have this laugh that doesn't apologize for itself. I love that.",
  "Music isn't just something you listen to. It's something you actually feel. I've never met someone who does that the way you do.",
  "You picked me. Out of everyone. I don't think I'll ever fully get over that.",
  "Nobody else says my name the way you do. There's something in it I can't describe.",
  "You finish a book and you carry it around with you for days. Like it's still happening. I think that's beautiful.",
  "You don't quit things that matter to you. Even when it's hard. Especially when it's hard.",
  "You try to hide how soft you are sometimes but I see it. I've always seen it. It's one of the best things about you.",
  "You make Tuesday feel worth remembering. That's not nothing.",
  "Every playlist you make is like a little map of your mood. I pay attention to all of them.",
  "You do kind things for people without making a thing of it. Just quietly. I notice.",
  "The way your whole face changes when you're excited about something. I would do a lot to keep seeing that.",
  "You're not pretending to be something you're not. In a world full of people performing, you just... are. And it's enough. More than enough.",
  "The day you said yes to me was the day a lot of things finally made sense.",
  "You hold opinions. Real ones. You don't bend them just to make people comfortable.",
  "You make a home feel like home. Not just a place to be.",
  "You let yourself cry at things that are beautiful. I hope you never stop doing that.",
  "The way music moves through you is different from anyone I've ever known. It's like it goes straight in.",
  "You're brave in ways you don't even count as brave. I do though.",
  "May 2nd used to just be my birthday. Then it became the day I met you. Then the day I married you. That date carries so much now.",
  "You ask the kind of questions that make conversations actually go somewhere.",
  "The fact that you're hard to impress makes every single time I've managed it feel like a win.",
  "You don't fake liking things. I appreciate that more than you know.",
  "You feel things honestly. Even when it would be easier not to.",
  "I've seen you exhausted, frustrated, completely at your limit. I loved you in all of it.",
  "Something happens to time when you play guitar. It slows down. I'm convinced of it.",
  "You remember things. Small things. Details from conversations months ago. It matters.",
  "Libraries are your happy place and I think that's one of the coolest things about you.",
  "Your humor sneaks up on people. They don't see it coming and then suddenly it's there.",
  "We've argued. More than once. I never once stopped loving you during any of it.",
  "You make me want to be someone I'm not embarrassed about.",
  "Your gut instincts are good. Like genuinely good. You should trust them more.",
  "You give without keeping a running total. That's rarer than it sounds.",
  "Late night fast food with you is better than anything fancy without you. By a lot.",
  "Home isn't a place for me right now. It's wherever you are.",
  "Your voice. Speaking, laughing, singing. I could listen to it for the rest of my life and not get tired.",
  "You showed up for me when things were hard. I haven't forgotten that and I won't.",
  "You see things other people walk straight past. Little beautiful things. I love that about you.",
  "You love deeply even when loving deeply scares you. That takes guts.",
  "You are exactly who you are. Not a performance of it. Just you. And that is everything.",
  "When you love someone you really love them. There's no half-measures with you.",
  "Every song you've played has felt like something I was lucky to get to hear.",
  "Sometimes you look at me and I genuinely can't believe I'm the one you chose.",
  "You take up exactly the right amount of space in a room. Not too much. Not too little.",
  "Your curiosity is contagious. You make things interesting just by being interested in them.",
  "You've made me more honest about what I feel. That's because of you. Fully because of you.",
  "You have grace. Real grace. Not the performed kind.",
  "I understand your bad moods. I understand most things about you in a way I've never understood anyone.",
  "You chose to build something with me. Every day I'm grateful for that.",
  "First thing in the morning. Last thing at night. You.",
  "When you sing to yourself, not performing, just existing — that's when I fall for you over and over again.",
  "I believe in right place right time because of us.",
  "You've never once made me feel like I had to be different.",
  "Your taste in music is genuinely great and I'll argue with anyone who says otherwise.",
  "You feel things all the way through. Not everyone can do that.",
  "You're calm when I need calm and you're fire when I need that too.",
  "I don't have to explain myself to you. You just know. That's not something I take for granted.",
  "You're the person I want to tell things to. Everything. Always.",
  "Every time I think I've hit the ceiling of how much I love you I find out there's more.",
  "You make me laugh in a way that gets all the way in.",
  "You exist. In the same world as me. I still find that kind of miraculous.",
  "You deserve to be loved on the days you forget that most. Especially those days.",
  "Everything good in my life has your fingerprints on it somewhere.",
  "You're patient with the things that deserve patience.",
  "A guitar looks different in your hands. More natural than in anyone else's.",
  "You have softness and strength living next to each other in you. Most people only get one.",
  "I don't fall for you once and stay there. I keep falling. Over and over. For you.",
  "Every library that's had you in it was better for it.",
  "You are my favorite version of everything.",
  "Different life, different world — I'd find you. I'd choose you. Every time.",
  "You make people feel like they matter when you're taking care of them. That's a gift.",
  "Your eyes say things before your words get there. I like being able to read them.",
  "You're the realest person I know. And real is what I've always needed.",
  "You're just yourself. Genuinely. Without apology. That kind of confidence is rare.",
  "Loving you has been the most important thing I've done.",
  "The world is better because you're in it. I mean that.",
  "When I picture the future I'm not filling in details. I'm just picturing you.",
  "You're not just my wife. You're my person.",
  "There is no version of a good life I can imagine that doesn't have you in it.",
  "Being loved by you is the best thing that's ever happened to me.",
  "A meal together. A song. A quiet night. With you these feel like things worth keeping forever.",
  "I'm not afraid of time passing as long as I'm passing it with you.",
  "Bebo. Just because you're Bebo.",
  "You've never made loving me feel like a burden.",
  "You're the answer to things I didn't know I was wondering.",
  "I'm more certain of you every single day. More, not less.",
  "The day I met you something in me went quiet. Like it had finally found where it belonged.",
  "You are mine and I am yours and honestly what else is there.",
  "Even the hard days are lighter because you exist.",
  "You haven't changed into someone I don't recognize. You're still you. I love that.",
  "I don't have a reason. I just love you. That's it.",
  "You are entirely, completely, irreplaceably yourself.",
  "The way you move through the world — I've never found the right words for it. I just know I want to keep watching.",
  "Last person I want to talk to before I sleep. First one I want to see when I wake up.",
  "You hold people carefully. That's the only way I know how to describe it.",
  "You change the temperature of a room just by walking into it. In the best way.",
  "You've been there for me in ways I couldn't have asked for. And you never made me feel like you were keeping score.",
  "When you sing softly to yourself the whole world goes a little quieter.",
  "You're worth writing things for. Worth building things for.",
  "There is nowhere on earth I'd rather be than where you are.",
  "You're proof that love doesn't fade when it's real. It just gets more.",
  "I've loved you through hard seasons. I'll love you through every one that comes.",
  "You've made my life so full I sometimes forget this is real.",
  "Ayesha Islam. The most important name I know.",
  "You're not a chapter. You're the whole story.",
  "I love you because of everything you are. Not in spite of any of it.",
  "You're extraordinary. On the days you feel it and especially on the days you don't.",
  "This page exists because of how much I love you. All of it.",
  "Some things don't need explaining. You're one of them.",
  "You're the song I keep coming back to no matter what else is playing.",
  "What I know best about you are the parts you'd call imperfections. I love those most.",
  "Watching you do something you love — genuinely love — is one of the best things I've ever gotten to see.",
  "You've made ordinary life feel like a privilege.",
  "The world is big and complicated and I'm just glad I'm walking through it next to you.",
  "I've never felt alone when you were around. Not once.",
  "You give love without keeping a tab. Not everyone can do that.",
  "Every time I've doubted myself you've been the voice that said keep going.",
  "Some of my happiest memories only exist because of you.",
  "Home, for me, means you. In every meaning of the word.",
  "This love didn't happen to me. It grew — slowly, quietly, completely — until there was no room for anything else.",
  "I'm proud of you. Genuinely. In a way I don't say enough.",
  "Us is my favorite story.",
  "Loving you has never once felt like giving something up.",
  "I found you. Out of everyone. I found you.",
  "Your strength doesn't look how people expect it to. It's realer for that.",
  "You carry joy in you like you were born with it.",
  "Bad days end better because you're somewhere in them.",
  "The sound of your voice is the most familiar thing I know.",
  "I trust you with the parts of me nobody else sees.",
  "I don't just stay with you out of habit. I choose you every day. On purpose.",
  "You have always been enough. More than enough.",
  "Love meant something smaller before you. You made it bigger.",
  "You are the kind of rare that doesn't come twice.",
  "Every good choice I've made has somehow pointed toward you.",
  "I love you today the same way I did at the beginning. With everything.",
  "You are the thing I'm most grateful for. Full stop.",
  "I hope when you read this you feel it — how completely loved you are.",
  "Something in me was already waiting before I met you. I think that now.",
  "You've given me every reason to stay. Not that I needed any.",
  "I've seen your heart up close. It's beautiful.",
  "I feel it all the time. Even when I don't say it. Always. For you.",
  "You're the best person I know.",
  "I keep trying to find the right words. I don't think they exist. But I keep trying.",
  "My Sinthia. My Bebo. My home.",
  "May 2nd gave me you. I'll spend every one after it being glad about that.",
  "A year of reasons isn't enough. It'll never be enough.",
  "Today, tomorrow, always. Without condition. Without end.",
  "This whole page barely touches what you mean to me.",
  "You are the most important thing.",
  "I'd do every bit of it again as long as it ends with you.",
  "Loving you is the easiest thing I've ever done.",
  "You're not just loved. You're cherished.",
  "I wrote a year's worth and the truth is I never needed a reason. I just love you.",
  "My wife. That word still feels like something I don't fully deserve.",
  "You changed my life by just being yourself.",
  "Some people look their whole lives for what I found in you.",
  "I'm still finding out how deep it goes. What I feel for you.",
  "I look at you and I see everything I wanted and things I didn't know to want.",
  "You've been there through the hard bits without flinching.",
  "You love fiercely and carefully at the same time. I don't know how you do both.",
  "Every morning you exist in the world and that makes everything feel manageable.",
  "My favorite accident. My most certain thing.",
  "You are genuinely, deeply good. I don't say that lightly.",
  "I've never been more like myself than when I'm with you.",
  "You're the kind of love people write songs about. Now you have a page.",
  "After everything. All the time. All the days. Still you. Always you.",
  "You deserve to know every day how remarkable you are.",
  "I'm still learning how to say it properly. What I feel.",
  "You're not in my story. You're why I wanted to write one.",
  "I could write a thousand more and still not get it right.",
  "The one thing I know for certain: I love you.",
  "You're it. Everything. Enough.",
  "The best parts of my life all have you in them.",
  "You're still surprising me. After all this time.",
  "I can't outgrow this. What I feel for you.",
  "You deserve love that shows up. I'm going to be that.",
  "You've been patient with me. More than I've said thank you for.",
  "Some days I look at you and just think — how.",
  "You've made ordinary moments mean something.",
  "I'd rather do nothing with you than anything without you.",
  "You stay. And staying takes everything. And you do it anyway.",
  "Having you in my life is the greatest thing that's happened to me.",
  "Wife never felt like a real word until it meant you.",
  "I know your laugh by heart.",
  "I know which silences are okay and which ones need words. Because I know you.",
  "You trusted me with your heart. I haven't forgotten what that means.",
  "You're beautiful. Not in a polite way. In the way that stops me in my tracks.",
  "All of this was never really about reasons. It was just another way to say: I love you.",
  "Every time you opened this page I hope you felt it. All of it.",
  "I'm nowhere near out of things to say.",
  "You're my Sinthia and I'm your Babai and nothing in this world makes more sense than that.",
  "I wrote this for you. All of it. Every word.",
  "On the days you feel invisible — you're not. You are seen. Known. Loved.",
  "Even when I'm not next to you, some part of me is.",
  "You've given me more than you know.",
  "Simply, quietly, endlessly. I love you.",
  "Every morning I choose you. That's not going to stop.",
  "You turned a life into a love story.",
  "Even heavy days are lighter because you're in them somewhere.",
  "The best decision I've ever made.",
  "I've watched you walk into a room and felt my whole body relax.",
  "You've been right and gracious about it. That says a lot about you.",
  "You're tender with people who don't always deserve it. That tells me everything about who you are.",
  "Watching you grow has been the greatest privilege of my life.",
  "You're the reason I believe love can actually feel like this. Natural. Easy. Right.",
  "You've brought so much lightness into my life.",
  "Tired, uncertain, overwhelmed — every version of you is someone I love completely.",
  "You are loyal in a way that is rare and I don't take it for granted.",
  "I learn from you. Constantly.",
  "Not one boring day. Not one.",
  "You're genuinely funny. I don't say that enough.",
  "You're a force. Quiet sometimes. But always a force.",
  "You've changed me in ways I'm still figuring out.",
  "The guitar, the books, the food, the music — all of it — I'd choose to love every bit of it again from scratch.",
  "You're not just the love of my life. You're the life of my love.",
  "I could keep going. I always could.",
  "I'm a better person because I know you.",
  "You letting me love you is not a small thing.",
  "You gave me a home inside a person.",
  "You're the answer even to things I forgot I was asking.",
  "My Sinthia. My everything.",
  "This page is just the beginning of it.",
  "I'll spend the rest of my life finding new ways to show you.",
  "Almost at the end of this year. Already thinking about the next one.",
  "365 days of saying it out loud. A whole lifetime of feeling it.",
  "This was never just a website. It was me trying to say: you are everything to me. I see you. I love you.",
  "You deserve this. And so much more.",
  "Fully. Finally. Forever. I love you.",
  "This is the last one for this year. Tomorrow I start again. Because with you there's always more.",
  "You're the reason always means something to me.",
  "Every version of forever I can think of — you're in all of them.",
  "The guitar sounds more honest when you're playing it. I've thought about why. I still don't know.",
  "You've never made me feel like I wasn't enough.",
  "I want to grow old with you. More every day.",
  "You make silence feel like a conversation.",
  "Your kindness isn't weakness. It's the most courageous thing about you.",
  "You make people feel warm before you've even said anything.",
  "You remember things. Dates. Details. The small stuff. It matters.",
  "You've shown me what it looks like to love someone without conditions.",
  "Hard days with you beat easy days without you. Every time.",
  "Full of noise, this world. You're the only frequency I actually want.",
  "I fell for you slowly and then all at once and I never came back from it.",
  "You made me believe in the kind of love I used to think was made up.",
  "You are a story worth telling.",
  "You matter. To me. To this world. More than you probably know.",
  "Grateful. Every day. For you.",
  "Not done. I'll never be done.",
  "You are loved. Completely. Endlessly. By me.",
];
